const { contextBridge, ipcRenderer } = require('electron');
const { injectBrowserAction } = require('electron-chrome-extensions/browser-action');

// Cria o elemento <browser-action-list> (ícones das extensões).
injectBrowserAction();

// Ponte segura entre a barra lateral (ui/index.html) e o processo principal.
contextBridge.exposeInMainWorld('browser', {
  newTab: () => ipcRenderer.send('tab:new'),
  toggleTree: (id) => ipcRenderer.send('tab:toggle-tree', id),
  closeTab: (id) => ipcRenderer.send('tab:close', id),
  tabMenu: (id) => ipcRenderer.send('tab:menu', id),
  openPin: (id) => ipcRenderer.send('pin:open', id),
  closePin: (id) => ipcRenderer.send('pin:close', id),
  pinMenu: (id) => ipcRenderer.send('pin:menu', id),
  movePin: (id, toIndex) => ipcRenderer.send('pin:move', id, toIndex),
  pinTab: (tabId) => ipcRenderer.send('pin:add', tabId),
  sleepTab: (id) => ipcRenderer.send('tab:sleep', id),
  splitDragStart: (id) => ipcRenderer.send('split:drag-start', id),
  splitDragEnd: () => ipcRenderer.send('split:drag-end'),
  activate: (id) => ipcRenderer.send('tab:activate', id),
  moveTab: (id, toIndex) => ipcRenderer.send('tab:move', id, toIndex),
  toggleMute: (id) => ipcRenderer.send('tab:mute', id),
  toggleSidebar: () => ipcRenderer.send('ui:toggle-sidebar'),
  switchSpace: (id) => ipcRenderer.send('space:switch', id),
  cycleSpace: (step) => ipcRenderer.send('space:cycle', step),
  spaceMenu: (id) => ipcRenderer.send('space:menu', id),
  manageSpaces: () => ipcRenderer.send('space:manage'),
  spacePicker: () => ipcRenderer.send('space:picker'),
  focusAddress: () => ipcRenderer.send('ui:focus-address'),
  toggleAi: () => ipcRenderer.send('ai:toggle'),
  translate: (lang) => ipcRenderer.send('translate:start', lang),
  stopTranslate: () => ipcRenderer.send('translate:stop'),
  toggleTranslation: () => ipcRenderer.send('translate:toggle'),
  setHover: (open) => ipcRenderer.send('ui:hover', open),
  openPage: (name) => ipcRenderer.send('ui:open-page', name),
  togglePanel: (name) => ipcRenderer.send('ui:panel', name),
  toggleBookmark: () => ipcRenderer.send('bookmark:toggle'),
  toggleAdblockSite: () => ipcRenderer.send('adblock:toggle-site'),
  openPopup: () => ipcRenderer.send('popup:open'),
  dismissPopup: () => ipcRenderer.send('popup:dismiss'),
  openBookmark: (url, newTab) => ipcRenderer.send('bookmark:open', url, newTab),
  suggest: (text) => ipcRenderer.invoke('suggest', text),
  find: (text, options) => ipcRenderer.send('find:query', text, options),
  stopFind: () => ipcRenderer.send('find:stop'),
  resetZoom: () => ipcRenderer.send('zoom:reset'),
  go: (text) => ipcRenderer.send('nav:go', text),
  back: () => ipcRenderer.send('nav:back'),
  forward: () => ipcRenderer.send('nav:forward'),
  reload: () => ipcRenderer.send('nav:reload'),
  stop: () => ipcRenderer.send('nav:stop'),
  home: () => ipcRenderer.send('nav:home'),
  onState: (cb) => ipcRenderer.on('state', (_e, state) => cb(state)),
  onFocusAddress: (cb) => ipcRenderer.on('focus-address', () => cb()),
  onFindOpen: (cb) => ipcRenderer.on('find-open', () => cb()),
  onFindClose: (cb) => ipcRenderer.on('find-close', () => cb()),
  onFindResult: (cb) => ipcRenderer.on('find-result', (_e, result) => cb(result)),
});
